[package]
name = "microbe"
version = "0.1.0"
authors = ["thatlittlegit <personal@thatlittlegit.tk>"]

[dependencies]
nickel = "0.10.1"
log = "0.4.1"
simple_logger = "0.5.0"
chrono = "0.4.2"
slugify = "0.1.0"
uuid = { version = "0.6.3", features = ["v5"] }
